# Generated by Django 3.2.8 on 2021-10-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=25)),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('isCompleted', models.BooleanField()),
                ('order', models.JSONField()),
            ],
        ),
    ]
